repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ["--manifest-path", "wasm-engine/Cargo.toml"]
        pass_filenames: false
      - id: clippy
        args: ["--manifest-path", "wasm-engine/Cargo.toml"]
        pass_filenames: false
